name: Test

on: [push]

jobs:
  test:
    # где запускаем
    runs-on: ubuntu-latest
    steps:
      # выкачиваем репо
      - uses: actions/checkout@v5
      # настраиваем java
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      # запуск тестов
      - run: ./gradlew clean test